"""Plain-language explanation of a backtest, built from the backtest's own numbers.

Every figure in the text is read from the result. Nothing is generated by a language model, so nothing can be invented
or changed. The sections follow the report a reader needs: the bottom line, what was tested, the headline numbers,
the full-period table, what each check means, in-sample against out-of-sample, the problems the test shows, and what to
do next. The wording changes with the result, so a strategy that did well is not described as if it did badly.
"""

from typing import Optional

CHECK_MEANING = {
    "Out-of-sample vs in-sample": "Whether the rules did better on the later dates than on the earlier ones. A much better later period usually means the market helped, not the rules.",
    "Enough trades": "Whether there are enough round trips for the numbers not to rest on a handful of trades.",
    "Beats same-basket buy-and-hold, risk-adjusted": "The fair test: the rules against the same stocks held the whole time, compared on return per unit of risk.",
    "Beats SPY, risk-adjusted": "The rules against the S&P 500 index, on return per unit of risk. It mixes stock choice with the rules, so it is context, not the main test.",
    "Deflated Sharpe": "How likely the risk-adjusted return is to be above zero, after counting how many rule variants were tried.",
    "Walk-forward windows": "How many six-month periods the rules beat the same stocks in. Four or five of five is a pass; one of five is a fail.",
    "Stable to small changes": "Whether moving each threshold a little changes the result a lot. A wide swing means the result depends on one exact number.",
    "Protective exit": "Whether the rules have a stop loss, trailing stop, or time stop to limit a single bad trade.",
}


def _pct(v: Optional[float], digits: int = 1) -> str:
    return "–" if v is None else f"{v:+.{digits}f}%"


def _plain(v: Optional[float], digits: int = 2) -> str:
    return "–" if v is None else f"{v:.{digits}f}"


def _pts(v: Optional[float]) -> str:
    return "–" if v is None else f"{v:+.1f} pts"


def _rule_text(rule: dict) -> str:
    field = str(rule.get("field", "")).replace("_", " ")
    op = {"crosses_above": "crosses above", "crosses_below": "crosses below", "is": "is", "is_not": "is not"}.get(
        rule.get("op"), rule.get("op"))
    return f"{field} {op} {rule.get('value')}"


def _bottom_line(result: dict) -> str:
    s, b, spy = result["strategy"], result["basket"], result["benchmark_spy"]
    s_cagr, b_cagr, spy_cagr = s.get("cagr_pct"), b.get("cagr_pct"), spy.get("cagr_pct")
    if s_cagr is None or b_cagr is None:
        return "There is not enough history to compare the rules with holding the same stocks."
    gap = s_cagr - b_cagr
    pieces = [f"Over this period the rules grew {_pct(s_cagr)} a year, against {_pct(b_cagr)} a year for holding the same stocks"]
    if spy_cagr is not None:
        pieces.append(f"and {_pct(spy_cagr)} a year for SPY")
    sentence = " ".join(pieces) + "."
    if gap < 0:
        sentence += " The rules made less money than holding."
    else:
        sentence += " The rules made more money than holding."
    if s.get("volatility_pct") is not None and b.get("volatility_pct") is not None and s["volatility_pct"] < b["volatility_pct"]:
        sentence += f" They were also calmer: volatility {_plain(s['volatility_pct'], 1)}% against {_plain(b['volatility_pct'], 1)}%."
    sh_s, sh_b = s.get("sharpe"), b.get("sharpe")
    if sh_s is not None and sh_b is not None:
        if sh_s <= sh_b:
            sentence += f" On risk-adjusted terms they still did not beat holding (Sharpe {_plain(sh_s)} against {_plain(sh_b)})."
        else:
            sentence += f" On risk-adjusted terms they beat holding (Sharpe {_plain(sh_s)} against {_plain(sh_b)})."
    return sentence


def _tested(result: dict, definition: dict) -> list[dict]:
    entry = [_rule_text(r) for r in definition.get("entry", [])] or ["(no buy rule)"]
    exits = [_rule_text(r) for r in definition.get("exit", [])]
    stops = []
    ex = definition.get("exits") or {}
    if ex.get("stop_loss_pct") is not None:
        stops.append(f"stop loss {ex['stop_loss_pct']}% below the buy price")
    if ex.get("trailing_stop_pct") is not None:
        stops.append(f"trailing stop {ex['trailing_stop_pct']}% below the highest price since buying")
    if ex.get("time_stop_sessions") is not None:
        stops.append(f"time stop after {ex['time_stop_sessions']} trading days")
    if ex.get("take_profit_pct") is not None:
        stops.append(f"take profit at +{ex['take_profit_pct']}%")
    sell = "; ".join(exits + stops) or "(no sell rule)"
    period = result.get("period", {})
    costs = result.get("costs", {})
    rows = [
        {"item": "Buy rule", "setting": " and ".join(entry), "plain": "Buy when every buy condition is true."},
        {"item": "Sell rule", "setting": sell, "plain": "Sell when any sell condition is true, or a stop is hit."},
        {"item": "Re-entry wait", "setting": f"{result.get('cooldown_sessions', 0)} trading days",
         "plain": "After selling, wait this long before buying the same stock again."},
        {"item": "Stocks", "setting": f"{len(result.get('tickers', []))} stocks: " + ", ".join(result.get("tickers", [])),
         "plain": "The stocks tested, held at the weights you set (or equal weights)."},
        {"item": "Period", "setting": f"{period.get('start', '–')} to {period.get('end', '–')} ({period.get('sessions', '–')} trading days)",
         "plain": "The dates the test covers."},
        {"item": "Trading costs", "setting": f"{costs.get('cost_bps_per_side', '–')} bps fee + {costs.get('slippage_bps_per_side', '–')} bps slippage per side",
         "plain": "Charged on every buy and every sell."},
        {"item": "Activity", "setting": f"{result.get('trades', '–')} round trips, about {_plain(result.get('trades_per_year'), 0)} a year",
         "plain": "Each round trip is one buy and one sell."},
    ]
    return rows


def _headline(result: dict) -> list[str]:
    s, b, spy = result["strategy"], result["basket"], result["benchmark_spy"]
    out = []
    if s.get("cagr_pct") is not None and b.get("cagr_pct") is not None:
        out.append(f"Excess CAGR vs holding the same stocks: {_pts(s['cagr_pct'] - b['cagr_pct'])} a year. The gap is in percentage points, not a return.")
    if s.get("cagr_pct") is not None and spy.get("cagr_pct") is not None:
        out.append(f"Excess CAGR vs SPY: {_pts(s['cagr_pct'] - spy['cagr_pct'])} a year.")
    if s.get("sharpe") is not None and spy.get("sharpe") is not None:
        out.append(f"Sharpe vs SPY: {_plain(s['sharpe'])} against {_plain(spy['sharpe'])}. Sharpe is return earned per unit of ups and downs.")
    return out


def _full_period(result: dict) -> list[dict]:
    rows = []
    for label, key in (("Strategy (rules)", "strategy"), ("Same stocks, held", "basket"), ("SPY", "benchmark_spy")):
        m = result[key]
        rows.append({
            "label": label,
            "total": _pct(m.get("total_return_pct")),
            "cagr": _pct(m.get("cagr_pct")),
            "volatility": _plain(m.get("volatility_pct"), 1) + "%" if m.get("volatility_pct") is not None else "–",
            "max_drop": _pct(m.get("max_drawdown_pct")),
            "sharpe": _plain(m.get("sharpe")),
            "worst_month": _pct(m.get("worst_month_pct")),
            "turnover": f"{_plain(m.get('turnover_pct_per_year'), 0)}%" if m.get("turnover_pct_per_year") is not None else "–",
        })
    drag = (result.get("cost_drag") or {}).get("cagr_points")
    rows[0]["cost_drag"] = f"{_plain(drag)} pts a year" if drag is not None else "–"
    rows[1]["cost_drag"] = "–"
    rows[2]["cost_drag"] = "–"
    return rows


def _checks(result: dict) -> list[dict]:
    return [{
        "label": c.get("label"),
        "status": c.get("status"),
        "detail": c.get("detail"),
        "meaning": CHECK_MEANING.get(c.get("label"), ""),
    } for c in result.get("checks", [])]


def _in_vs_out(result: dict) -> Optional[dict]:
    ins, out = result.get("in_sample"), result.get("out_of_sample")
    if not ins or not out or ins.get("cagr_pct") is None or out.get("cagr_pct") is None:
        return None
    if out["cagr_pct"] > ins["cagr_pct"] + 5:
        note = ("The rules did much better on the later dates than the earlier ones. That usually means the recent "
                "market helped, not the rules.")
    elif out["cagr_pct"] < ins["cagr_pct"] - 5:
        note = "The rules did worse on the later dates than the earlier ones, so they may not hold up in recent markets."
    else:
        note = "The rules did about the same on both periods, which is what a steady rule should show."
    return {
        "in_sample": {"cagr": _pct(ins["cagr_pct"]), "volatility": _plain(ins.get("volatility_pct"), 1) + "%", "max_drop": _pct(ins.get("max_drawdown_pct")), "sharpe": _plain(ins.get("sharpe"))},
        "out_of_sample": {"cagr": _pct(out["cagr_pct"]), "volatility": _plain(out.get("volatility_pct"), 1) + "%", "max_drop": _pct(out.get("max_drawdown_pct")), "sharpe": _plain(out.get("sharpe"))},
        "note": note,
    }


def _problems(result: dict) -> list[str]:
    problems = []
    s, b = result["strategy"], result["basket"]
    if s.get("sharpe") is not None and b.get("sharpe") is not None and s["sharpe"] <= b["sharpe"]:
        problems.append("Against the same stocks held, the rules lost on risk-adjusted return. That is the fairest comparison.")
    wf = result.get("walk_forward") or {}
    share = wf.get("beat_basket_pct")
    if share is not None and share < 60:
        problems.append(f"The rules beat the same stocks in only {wf.get('beat_basket_windows')} of {wf.get('test_windows')} six-month windows. Losing most windows is a weak result.")
    sens = result.get("sensitivity") or {}
    if sens.get("widest_swing") is not None and sens["widest_swing"] > 0.5:
        problems.append("A small change to one threshold changes the Sharpe a lot, so the result depends on that exact number.")
    tickers = set(result.get("tickers", []))
    if {"GOOG", "GOOGL"} <= tickers:
        problems.append("The stocks include both GOOG and GOOGL. They are the same company, so it counts twice.")
    trades = result.get("trades") or 0
    if trades and trades < 30:
        problems.append(f"Only {trades} round trips. A handful of trades proves little.")
    exposure = result.get("exposure_pct")
    if exposure is not None and exposure < 60:
        problems.append(f"The rules were invested only {_plain(exposure, 0)}% of the time. Part of any calmer ride comes from sitting in cash.")
    top = result.get("top_ticker") or {}
    if top.get("flag"):
        problems.append(f"{top.get('ticker')} produced {_plain(top.get('share_pct'), 0)}% of the total gain. The verdict depends on that one stock.")
    dsr = result.get("deflated_sharpe") or {}
    if dsr.get("variants", 1) and dsr.get("variants", 1) > 1:
        problems.append(f"{dsr['variants']} rule variants were tried. The more variants tried, the more likely a good result is luck.")
    for w in result.get("state_warnings", []) or []:
        problems.append(w)
    return problems


def _next_steps(result: dict) -> list[str]:
    steps = []
    s, b = result["strategy"], result["basket"]
    if s.get("cagr_pct") is not None and b.get("cagr_pct") is not None and s["cagr_pct"] < b["cagr_pct"]:
        steps.append("Compare at the same risk: hold the same stocks mixed with cash or bonds at the strategy's volatility. If that mix earns more, the rules add nothing a simpler allocation cannot.")
    steps.append("Test on other stocks: run the same rules on random S&P 500 samples. Hand-picked stocks can flatter or hide how rules behave on typical stocks.")
    steps.append("Test a longer history, so the test covers more than one kind of market, including a crash.")
    steps.append("Decide the rules before testing, and do not change the numbers to make a test look better.")
    return steps


def explain_backtest(result: dict, definition: dict) -> dict:
    return {
        "bottom_line": _bottom_line(result),
        "tested": _tested(result, definition),
        "headline": _headline(result),
        "full_period": _full_period(result),
        "checks": _checks(result),
        "in_vs_out": _in_vs_out(result),
        "problems": _problems(result),
        "next_steps": _next_steps(result),
        "disclaimer": "Past results, not a forecast or a recommendation. Nothing is bought or sold by this test.",
    }
